### ISSUE TITLE
FIle image picker doesn't work on latest IOS 14

### ISSUE THREAD

**Issue by lecicdjuro** [miguelpruivo/flutter_file_picker#405]
file_picker:2.0.1+1

**Describe the bug**
I have granted photos permission before a pick image files, and after i pick one, i got an error
 * -[FilePickerPlugin picker:didFinishPicking:] [Line 351]
2020-09-23 13:12:41.697062+0200 Runner[1342:413734] [default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened

**Issue details**
1. IOS
2. 14
3. jpg
4. pick a single file type image

**Error Log**
 * -[FilePickerPlugin picker:didFinishPicking:] [Line 351]
2020-09-23 13:12:41.697062+0200 Runner[1342:413734] [default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened

**Flutter Version details**
1.22.0-12.1.pre

**Comment by miguelpruivo** [comment]
Related to #406.

**Comment by miguelpruivo** [comment]
@lecicdjuro  this should be fixed with 2.0.1+2. Would you mind give it a try and see if it's working for you?

**Comment by lecicdjuro** [comment]
@miguelpruivo  The issue is still present. After few attempts to choose image or video, app will frezze

**Comment by miguelpruivo** [comment]
@lecicdjuro yes, there’s still an issue with it for iOS 14. I’m investigating.

**Comment by miguelpruivo** [comment]
Hey y'all, could you please give it a try pointing to:
```
file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker
      ref: fix/ios14-picker
```
And let me know if it's working for you?

There are still a few minor issues with the PHPicker on their end (Apple) that have been reported and they're fixing it, but it should be stable enough for it to work.

**Comment by miguelpruivo** [comment]
This should be fixed with 2.0.6.

Feel free to reopen this or report on #407 if you still encounter any issue related to it.

Thank you!

**Comment by adnankhan74444** [comment]
[ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }

**Comment by miguelpruivo** [comment]
@adnankhan74444 ignore it. That hasn't any effect.

**Comment by sproutlyCaleb** [comment]
I am getting this error. 

file_picker: ^4.2.7


***** Picker:<PHPickerViewController: 0x10af2a2b0> didFinishPicking:(
    "<PHPickerResult: 0x2833bf240>",
    "<PHPickerResult: 0x2833a2f40>",
    "<PHPickerResult: 0x2833a3800>"
)
* -[FilePickerPlugin picker:didFinishPicking:] [Line 401]
[default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }
[default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }
[default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }
Error copying file type public.item. Error: Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x283d0aeb0 {Error Domain=NSCocoaErrorDomain Code=4101 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x283d000c0 {Error Domain=PHAssetExportRequestErrorDomain Code=3 "(null)" UserInfo={NSUnderlyingError=0x283d0b9c0 {Error Domain=CloudPhotoLibraryErrorDomain Code=1005 "Disk space is very low" UserInfo=0x28338ae80 (not displayed)}}}}}}



***** Could not load the picked given file: Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x283d0aeb0 {Error Domain=NSCocoaErrorDomain Code=4101 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x283d000c0 {Error Domain=PHAssetExportRequestErrorDomain Code=3 "(null)" UserInfo={NSUnderlyingError=0x283d0b9c0 {Error Domain=CloudPhotoLibraryErrorDomain Code=1005 "Disk space is very low" UserInfo=0x28338ae80 (not displayed)}}}}}}
* -[FilePickerPlugin picker:didFinishPicking:]_block_invoke [Line 428]
Error copying file type public.item. Error: Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x283d12430 {Error Domain=NSCocoaErrorDomain Code=4101 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x283d08c30 {Error Domain=PHAssetExportRequestErrorDomain Code=3 "(null)" UserInfo={NSUnderlyingError=0x283d0a7c0 {Error Domain=CloudPhotoLibraryErrorDomain Code=1005 "Disk space is very low" UserInfo=0x28338be20 (not displayed)}}}}}}
