### ISSUE TITLE
Crashing on iOS 10.0 and above when file is selected.

### ISSUE THREAD

**Issue by RalphMarvin** [miguelpruivo/flutter_file_picker#419]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform (Android/iOS)
2. Platform OS version
3. File type (filter) — when applicable
4. Detailed steps to reproduce

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
Hi, @RalphMarvin, could you please elaborate? This issue hasn’t any details.

**Comment by RalphMarvin** [comment]
Immediately a file is selected, the app just crashes. But on Android
everything works fine. It doesn't give any build time error(s) or
warning(s), the behaviour occurs at runtime.

**Comment by miguelpruivo** [comment]
@RalphMarvin which iOS version are you using and `file_picker`? 

There was an issue with iOS 14 which is fixed on latest file_picker version.

**Comment by davidAg9** [comment]
> @RalphMarvin which iOS version are you using and `file_picker`?
> 
> There was an issue with iOS 14 which is fixed on latest file_picker version.

I think the issue is still present ,my app crushing when I invoke the file picker

**Comment by miguelpruivo** [comment]
@davidAg9 I need more details.

**Comment by RalphMarvin** [comment]
> > @RalphMarvin which iOS version are you using and `file_picker`?
> > There was an issue with iOS 14 which is fixed on latest file_picker version.
> 
> I think the issue is still present ,my app crushing when I invoke the file picker

Yes the crashing still exists. I have installed the latest version of the plugin but it still crashes.

**Comment by RalphMarvin** [comment]
> @davidAg9 I need more details.

This is from my flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Am targeting iOS version 10.0 and higher.
Below is my Podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by miguelpruivo** [comment]
Hi, I need the stack trace when the crash happens.

**Comment by miguelpruivo** [comment]
Closing due to inactivity. Feel free to reopen if you still have this issue. Thank you!

**Comment by sachin052** [comment]
`2020-10-23 21:00:26.818794+0530 Runner[91857:670094] [DocumentManager] Failed to associate thumbnails for picked URL file:///Users/skycap/Library/Developer/CoreSimulator/Devices/BC4CED43-E4C8-4E77-BC23-E17A59B2C002/data/Containers/Shared/AppGroup/55173163-9493-406D-A4B1-A3E95A303F0F/File%20Provider%20Storage/Downloads/SampleVideo_1280x720_1mb.mp4 with the Inbox copy file:///Users/skycap/Library/Developer/CoreSimulator/Devices/BC4CED43-E4C8-4E77-BC23-E17A59B2C002/data/Containers/Data/Application/B5261C2C-CB1E-4535-8ACC-6A9195C432E6/tmp/com.skycap.colibri-Inbox/SampleVideo_1280x720_1mb.mp4: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x600001c33b40 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
2020-10-23 21:00:27.627608+0530 Runner[91857:669516] -[NSNull length]: unrecognized selector sent to instance 0x7fff80615710
2020-10-23 21:00:27.680274+0530 Runner[91857:669516] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x7fff80615710'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6ff94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c53dac ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x00007fff257881ab -[NSURL(NSURL) initFileURLWithPath:] + 68
	6   Foundation                          0x00007fff25788b64 +[NSURL(NSURL) fileURLWithPath:] + 45
	7   video_thumbnail                     0x000000010c719551 -[VideoThumbnailPlugin handleMethodCall:result:] + 1905
	8   Flutter                             0x000000010a9a95be __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	9   Flutter                             0x000000010a190076 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	10  Flutter                             0x000000010a194e18 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	11  Flutter                             0x000000010a4e162b _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_33NS_9allocatorIS8_EEFvvEEclEv + 83
	12  Flutter                             0x000000010a19cd56 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 160
	13  Flutter                             0x000000010a1a1ac6 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	14  CoreFoundation                      0x00007fff23bb2944 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	15  CoreFoundation                      0x00007fff23bb2632 __CFRunLoopDoTimer + 1026
	16  CoreFoundation                      0x00007fff23bb1c8a __CFRunLoopDoTimers + 266
	17  CoreFoundation                      0x00007fff23bac9fe __CFRunLoopRun + 2238
	18  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	19  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	20  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	21  Runner                              0x000000010998de7b main + 75
	22  libdyld.dylib                       0x00007fff51a1dc25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by sachin052** [comment]
> Hi, I need the stack trace when the crash happens.

`2020-10-23 21:00:26.818794+0530 Runner[91857:670094] [DocumentManager] Failed to associate thumbnails for picked URL file:///Users/skycap/Library/Developer/CoreSimulator/Devices/BC4CED43-E4C8-4E77-BC23-E17A59B2C002/data/Containers/Shared/AppGroup/55173163-9493-406D-A4B1-A3E95A303F0F/File%20Provider%20Storage/Downloads/SampleVideo_1280x720_1mb.mp4 with the Inbox copy file:///Users/skycap/Library/Developer/CoreSimulator/Devices/BC4CED43-E4C8-4E77-BC23-E17A59B2C002/data/Containers/Data/Application/B5261C2C-CB1E-4535-8ACC-6A9195C432E6/tmp/com.skycap.colibri-Inbox/SampleVideo_1280x720_1mb.mp4: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x600001c33b40 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
2020-10-23 21:00:27.627608+0530 Runner[91857:669516] -[NSNull length]: unrecognized selector sent to instance 0x7fff80615710
2020-10-23 21:00:27.680274+0530 Runner[91857:669516] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x7fff80615710'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6ff94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c53dac ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x00007fff257881ab -[NSURL(NSURL) initFileURLWithPath:] + 68
	6   Foundation                          0x00007fff25788b64 +[NSURL(NSURL) fileURLWithPath:] + 45
	7   video_thumbnail                     0x000000010c719551 -[VideoThumbnailPlugin handleMethodCall:result:] + 1905
	8   Flutter                             0x000000010a9a95be __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	9   Flutter                             0x000000010a190076 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	10  Flutter                             0x000000010a194e18 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	11  Flutter                             0x000000010a4e162b _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_33NS_9allocatorIS8_EEFvvEEclEv + 83
	12  Flutter                             0x000000010a19cd56 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 160
	13  Flutter                             0x000000010a1a1ac6 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	14  CoreFoundation                      0x00007fff23bb2944 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	15  CoreFoundation                      0x00007fff23bb2632 __CFRunLoopDoTimer + 1026
	16  CoreFoundation                      0x00007fff23bb1c8a __CFRunLoopDoTimers + 266
	17  CoreFoundation                      0x00007fff23bac9fe __CFRunLoopRun + 2238
	18  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	19  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	20  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	21  Runner                              0x000000010998de7b main + 75
	22  libdyld.dylib                       0x00007fff51a1dc25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`
