### ISSUE TITLE
Temporary file could not be created.

### ISSUE THREAD

**Issue by whedamd** [miguelpruivo/flutter_file_picker#997]
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)

Platform: iOS

**Comment by gabdsg** [comment]
Same problem here

**Comment by nobezawa** [comment]
Have the same problem.

my version
```yaml
file_picker:
    dependency: "direct main"
    description:
      name: file_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.5.1"
```

Execution environment
```
iPhone Simulator: iPhone11
iOS: 15.2
```

**Comment by MyisCARRY** [comment]
I am having the same problem. I am using this method:

> await FilePicker.platform.pickFiles(type: FileType.image);

Message:

> Temporary file could not be created

Details:

> Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x600002ed33f0 {Error Domain=NSCocoaErrorDomain Code=4101 "Błąd komunikacji z aplikacją pomocniczą." UserInfo={NSUnderlyingError=0x600002e7cd80 {Error Domain=PHAssetExportRequestErrorDomain Code=0 "Nie można ukończyć tej operacji. (Błąd PHAssetExportRequestErrorDomain 0.)" UserInfo={NSLocalizedDescription=Nie można ukończyć tej operacji. (Błąd PHAssetExportRequestErrorDomain 0.), NSUnderlyingError=0x600002e7fd20 {Error Domain=PAMediaConversionServiceErrorDomain Code=2 "Nie można ukończyć tej operacji. (Błąd PAMediaConversionServiceErrorDomain 2.)" UserInfo=0x60000205b500 (not displayed)}}}}}}

Error from logs:

> flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x600002ed33f0 {Error Domain=NSCocoaErrorDomain Code=4101 "Błąd komunikacji z aplikacją pomocniczą." UserInfo={NSUnderlyingError=0x600002e7cd80 {Error Domain=PHAssetExportRequestErrorDomain Code=0 "Nie można ukończyć tej operacji. (Błąd PHAssetExportRequestErrorDomain 0.)" UserInfo={NSLocalizedDescription=Nie można ukończyć tej operacji. (Błąd PHAssetExportRequestErrorDomain 0.), NSUnderlyingError=0x600002e7fd20 {Error Domain=PAMediaConversionServiceErrorDomain Code=2 "Nie można ukończyć tej operacji. (Błąd PAMediaConversionServiceErrorDomain 2.)" UserInfo=0x60000205b500 (not displayed)}}}}}}, null)

**Comment by neelansh-creatorstack** [comment]
Same issue happening with me on a real device.

**Comment by squaredx** [comment]
I'd like to say that I'm also experiencing this issue. I've been getting this issues on the Xcode simulator running  Xcode 13.3.1, iOS 15.4.1, and package version 4.5.1. I have yet to test on a physical device yet.

Before this issue only occurred on the pink flowers picture in the simulator but now its happening with **all** the pictures. The error message I am getting is:
```
flutter: unhandled element metadata; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#dd967(), name: "assets/svg/manage-memories-blankstate.svg", colorFilter: null)
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)
```

And the code I am using to call the file picker is:
```
final FilePickerResult? pickedFiles = await FilePicker.platform.pickFiles(
      type: FileType.media,
      allowMultiple: true,
      onFileLoading: (FilePickerStatus status) {
        print(status);
      },
    );
```

**Comment by whedamd** [comment]
Inside info.plist
<key>NSCameraUsageDescription</key>
	<string>Upload service request photos</string>
<key>NSPhotoLibraryUsageDescription</key>
	<string>Upload service request photos</string>
<key>UISupportsDocumentBrowser</key>
	<true/>

Package: image_picker: ^0.8.4+11
Implementation:
Uint8List? pickPhoto(ImageSource source) async {
    XFile file = await _picker.pickImage(source: source);
    if (file != null) {
      return Uint8List photo = await file.readAsBytes();
    }
    return null;
}

**Comment by pinguluk** [comment]
+1

**Comment by pinguluk** [comment]
Update: it seems that if you exclude **arm64** from **Excluded Architectures** from **Target -> Runner**, you'll get the error. If you remove it, it's working again.
In my case I need to exclude the arm64, because of another Pod that gets me another error, so I don't know what the best workaround or fix for this would be.
![image](https://user-images.githubusercontent.com/16257821/169044827-c0a329b5-b52b-4136-a609-b9bff9296125.png)

**Comment by yahu1031** [comment]
@miguelpruivo 
I tried with code block 
```dart
  /// Uploads the file to the device.
  /// This function will return the list of files.
  static Future<Set<PlatformFile>> uploadFile(
          [FileType? fileType,
          bool? allowMultipleFiles,
          List<String>? extensions]) async =>
      (await FilePicker.platform.pickFiles(
              type: fileType ?? FileType.any,
              allowMultiple: allowMultipleFiles ?? false,
              allowedExtensions: extensions))
          ?.files
          .toSet() ??
      <PlatformFile>{};
```

Called it here
```dart
IconButton(
  icon: const Icon(
    TablerIcons.photo,
    color: Colors.black,
  ),
  onPressed: () async {
    try {
      // await controller!.stopCamera();
      Set<PlatformFile> _file =
          await AppService.uploadFile(FileType.image);
      if (_file.isNotEmpty) {
        bool _gotData = await AppService.getQRData(
          _scaffoldKey.currentContext!,
          _file.first.path,
        );
        if (_gotData) {
          await Navigator.pushReplacementNamed(
              context, PageRoutes.activatingAtSign);
        }
      } else {
        await controller!.startCamera(onScan);
        await showToast(
            'No image picked', _scaffoldKey.currentContext!, true);
      }
    } on Exception catch (e) {
      await controller!.stopCamera();
      qrLog.severe(e);
      await showToast('Failed to pick image',
          _scaffoldKey.currentContext!, true);
    }
  },
),
```

And the below is result.

https://user-images.githubusercontent.com/35523357/173558737-48d9b63f-66c9-4628-9f69-fdbdf19d8ae1.mp4

**Comment by bawantha** [comment]
Why this issue is closed?

**Comment by conceptualben** [comment]
> You are probably trying with the pink flowers photo on the simulator — that's a known iOS simulator issue since iOS 14. You should "ignore it". 😄

I'm also experiencing this issue (Mac M1, iPhone Simulator with iOS 15.5). It looks like it was prematurely closed if the comment was the reason.

Looking at this similar package [image_picker](https://pub.dev/packages/image_picker) their readme states:

> As a result of implementing PHPicker it becomes impossible to pick HEIC images on the iOS simulator in iOS 14+. This is a known issue. Please test this on a real device, or test with non-HEIC images until Apple solves this issue.

If file_picker's case is the same it would be useful to know it!

**Comment by yahu1031** [comment]
May be this should be fixed from apple 😅

**Comment by WaheedHussainHaans** [comment]
I am not even picking that flower image but still getting that error on the Mac M1 chip. Any fixes ?

**Comment by JaFa13** [comment]
This is still not working

**Comment by phongkien** [comment]
Seems to be random. On my MacBox pro, it is fined, on M1 (used to work but no longer working).

**Comment by yahu1031** [comment]
This issue was not from your side, If you use older version of fluttertoast package it will reproduce it. But it was not fixed.

**Comment by NabeelAbid1812** [comment]
> I am not even picking that flower image but still getting that error on the Mac M1 chip. Any fixes ?

can I help you?

**Comment by WaheedHussainHaans** [comment]
@NabeelAbid1812 sure

**Comment by anasboyka** [comment]
same here still got the same problem... 19/12/2022

**Comment by donpui** [comment]
I also recently had the same issue on iphonesimulator with media picking. However, I managed to make it work by changing Document Storage to "On My iPhone" and restarting app.

**Comment by aakarapetyan** [comment]
also have the same problem. Any solution?
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x28309be40 {Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x28309a670 {Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 16965 on anonymousListener or serviceListener" UserInfo={NSDebugDescription=connection from pid 16965 on anonymousListener or serviceListener}}}}}, null)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x28309be40 {Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x28309a670 {Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 16965 on anonymousListener or serviceListener" UserInfo={NSDebugDescription=connection from pid 16965 on anonymousListener or serviceListener}}}}}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
<asynchronous suspension>
#2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:508:35)
<asynchronous suspension>
#3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:92:33)

**Comment by SmueezApex** [comment]
Facing the same issue as well. need t fix this ASAP

**Comment by fahad-whizpool** [comment]
I am facing this issue on real ios device.

**Comment by gonciuu** [comment]
Also facing the same issue on real iphone device

**Comment by Xarvis** [comment]
If I use the following settings on a physical iPhone, it will occur:
Settings -> Camera -> Formats -> Most Compatible

If I change it to High Efficiency, it works fine.

**Comment by Xarvis** [comment]
I am facing the same issue when I used the following settings on my physical iPhone:
Settings -> Camera -> Formats -> Most Compatible.

**Comment by sanalkv** [comment]
Faced the issue with live photos taken with iPhone camera app. If I turn off the live feature, I'm able to upload the image.

**Comment by TP-113** [comment]
https://github.com/miguelpruivo/flutter_file_picker/issues/997#issuecomment-2328044791
I have a same issue.

Different results were seen depending on the format of the image ("Settings" -> "Formats"). "High Efficiency" succeeded in picking in live photos, while "Most Compatible" failed.
![IMG_9359](https://github.com/user-attachments/assets/f23df3aa-a74b-4176-8b52-f1a020839c4e)

**Comment by bahadurh** [comment]
I have implemented a workaround for selecting multiple photos. Instead of failing completely, the process now retrieves the selected photos successfully. This improvement is included in PR #1639.
